wmde/fundraising-memberships

.travis.yml
Dockerfile
Makefile
composer.json
docker-compose.yml

Compare wmde/email-address.
Adds travis integration for the first time.

T183221 build on all supported php versions

---

src/MembershipContextFactory.php

Implement ServiceProvider so we can register (and override) the implemented services in FundraisingFrontend.

T183221 Configurable authorizer

---

composer.json
tests/Integration/DataAccess/DoctrineMembershipApplicationRepositoryTest.php

Update store repository in composer.json

---

composer.json
phpcs.xml
src/DataAccess/DoctrineApplicationAuthorizer.php
src/DataAccess/DoctrineApplicationPiwikTracker.php
src/DataAccess/DoctrineApplicationRepository.php
src/DataAccess/DoctrineApplicationTokenFetcher.php
src/DataAccess/DoctrineApplicationTracker.php
src/DataAccess/Internal/DoctrineApplicationTable.php
src/Domain/Repositories/StoreMembershipApplicationException.php
tests/Integration/DataAccess/Internal/DoctrineApplicationTableTest.php

As per https://github.com/wmde/FundraisingStore/pull/90
Put this in an "Internal" sub-NS to indicate this thing is package private. (The only place where it makes sense to use this is in the data access part of this BC.)

Add DoctrineApplicationTable

---

src/UseCases/CancelMembershipApplication/CancelMembershipApplicationUseCase.php

If a need arises for those it should be tracked in the issue tracker anyway

Remove ancient TODOs

---

composer.json

First change for Scrutinizer :)

Fix indent

---

src/Domain/Model/Application.php
src/Infrastructure/TemplateMailerInterface.php
src/UseCases/ApplyForMembership/ApplyForMembershipUseCase.php
src/UseCases/CancelMembershipApplication/CancelMembershipApplicationUseCase.php
src/UseCases/HandleSubscriptionSignupNotification/HandleSubscriptionSignupNotificationUseCase.php
tests/Fixtures/TemplateBasedMailerSpy.php
tests/Integration/UseCases/ApplyForMembership/ApplyForMembershipUseCaseTest.php
tests/Integration/UseCases/CancelMembershipApplication/CancelMembershipApplicationUseCaseTest.php

We need to know if the application is either active or sustaining so that we can change the subject.
T202862

Update email template handling for new content

---

src/UseCases/HandleSubscriptionSignupNotification/HandleSubscriptionSignupNotificationUseCase.php

Add additional values to subscription signup email

---

src/Domain/Model/Application.php
src/Infrastructure/TemplateMailerInterface.php
src/UseCases/ApplyForMembership/ApplyForMembershipUseCase.php
src/UseCases/CancelMembershipApplication/CancelMembershipApplicationUseCase.php
src/UseCases/HandleSubscriptionSignupNotification/HandleSubscriptionSignupNotificationUseCase.php
tests/Fixtures/TemplateBasedMailerSpy.php
tests/Integration/UseCases/ApplyForMembership/ApplyForMembershipUseCaseTest.php
tests/Integration/UseCases/CancelMembershipApplication/CancelMembershipApplicationUseCaseTest.php

Revert previous email subject changes

---

src/UseCases/ApplyForMembership/ApplyForMembershipUseCase.php
tests/Integration/UseCases/ApplyForMembership/ApplyForMembershipUseCaseTest.php

Needed for comment by Kai here:
https://phabricator.wikimedia.org/T202862#5152260

Add receipt flag to membership confirmation email

---

src/UseCases/CancelMembershipApplication/CancelMembershipApplicationUseCase.php

https://phabricator.wikimedia.org/T226958

Prevent multiple membership cancellation emails

---

tests/Integration/UseCases/CancelMembershipApplication/CancelMembershipApplicationUseCaseTest.php

Add test for duplicate cancel case

---

src/UseCases/HandleSubscriptionPaymentNotification/HandleSubscriptionPaymentNotificationUseCase.php
tests/Data/ValidPayPalNotificationRequest.php

This reverts commit ff63683ad51dafb78be8cc91b6dce8bcbbc54168.
This sis a followup for
https://github.com/wmde/fundraising-payments/pull/14

Revert "Update PPL date handling"

---

.gitignore
.travis.yml
composer.json
tests/Integration/DataAccess/Internal/DoctrineApplicationTableTest.php
tests/Integration/UseCases/ShowApplicationConfirmation/ShowApplicationConfirmationUseCaseTest.php

Can't update to 9.x because the covers-validator tool is nor compatible yet

Update PHPUnit to 8.x

---

Makefile
composer.json
phpstan.neon
src/DataAccess/DoctrineApplicationRepository.php
src/DataAccess/DoctrineApplicationTokenFetcher.php
tests/Integration/UseCases/ApplyForMembership/ApplyForMembershipUseCaseTest.php
tests/Integration/UseCases/HandleSubscriptionPaymentNotification/HandleSubscriptionPaymentNotificationUseCaseTest.php
tests/Integration/UseCases/HandleSubscriptionSignupNotification/HandleSubscriptionSignupNotificationUseCaseTest.php

Level 5 commit needs to be amended when https://github.com/wmde/FundraisingStore/pull/168 and #38 are merged

Increase PHPStan level

---

composer.json
phpcs.xml

Remove mediawiki phpcs extension

Update php codesniffer to 3.5

---

composer.json
src/DataAccess/DoctrineApplicationAuthorizer.php
src/DataAccess/DoctrineApplicationPiwikTracker.php
src/DataAccess/DoctrineApplicationRepository.php
src/DataAccess/DoctrineApplicationTracker.php
src/DataAccess/DoctrineEntities/MembershipApplication.php
src/DataAccess/DoctrineMembershipApplicationPrePersistSubscriber.php
src/DataAccess/Internal/DoctrineApplicationTable.php
src/DataAccess/MembershipApplicationData.php
src/MembershipContextFactory.php
tests/Data/ValidMembershipApplication.php
tests/Integration/DataAccess/DoctrineMembershipApplicationAuthorizerTest.php
tests/Integration/DataAccess/DoctrineMembershipApplicationRepositoryTest.php
tests/Integration/DataAccess/DoctrineMembershipApplicationTrackerTest.php
tests/Integration/DataAccess/Internal/DoctrineApplicationTableTest.php
tests/Integration/DataAccess/SerializedDataHandlingTest.php
tests/Integration/DoctrineEntities/MembershipApplicationInsertionTest.php
tests/SchemaCreator.php
tests/TestEnvironment.php
tests/TestMembershipContextFactory.php
tests/Unit/DoctrineEntities/MembershipApplicationTest.php

https://phabricator.wikimedia.org/T247744
Related pull requests:
- https://github.com/wmde/fundraising-donations/pull/85
- https://github.com/wmde/fundraising-subscriptions/pull/16

Remove FundraisingStore

---

.scrutinizer.yml
src/Domain/Event.php
src/Domain/Event/MembershipCreatedEvent.php
src/EventEmitter.php
src/UseCases/ApplyForMembership/ApplyForMembershipUseCase.php
tests/Fixtures/EventEmitterSpy.php
tests/Integration/UseCases/ApplyForMembership/ApplyForMembershipUseCaseTest.php

Add EventEmitter interface
Add Event Interface
Emit MembershipCreatedEvent in ApplyForMembershipUseCase
This is for https://phabricator.wikimedia.org/T253658

Add Domain Events

---

config/DoctrineClassMapping/WMDE.Fundraising.MembershipContext.Domain.Model.Incentive.dcm.xml
src/DataAccess/DoctrineApplicationRepository.php
src/DataAccess/DoctrineEntities/MembershipApplication.php
src/DataAccess/Exception/UnknownIncentive.php
src/Domain/Model/Application.php
src/Domain/Model/Incentive.php
src/MembershipContextFactory.php
src/UseCases/ApplyForMembership/ApplyForMembershipRequest.php
src/UseCases/ApplyForMembership/MembershipApplicationBuilder.php
tests/Data/ValidMembershipApplication.php
tests/Fixtures/ThrowingEntityManager.php
tests/Integration/DataAccess/DoctrineMembershipApplicationRepositoryTest.php
tests/Unit/Domain/Model/ApplicationTest.php
tests/Unit/Domain/Model/IncentiveTest.php
tests/Unit/UseCases/ApplyForMembership/MembershipApplicationBuilderTest.php

This is for https://phabricator.wikimedia.org/T270098

Add incentives

---

composer.json
src/DataAccess/DoctrineEntities/MembershipApplication.php
src/MembershipContextFactory.php
tests/Unit/UseCases/ApplyForMembership/MembershipApplicationValidatorTest.php

Update FUN coding style to version 2.0

---

composer.json

https://phabricator.wikimedia.org/T276215

Update payment context

---

src/UseCases/CancelMembershipApplication/CancelMembershipApplicationUseCase.php
src/UseCases/CancelMembershipApplication/CancellationResponse.php
src/UseCases/ModerateMembershipApplication/ModerateMembershipApplicationResponse.php
src/UseCases/ModerateMembershipApplication/ModerateMembershipApplicationUseCase.php
src/UseCases/RestoreMembershipApplication/RestoreMembershipApplicationResponse.php
src/UseCases/RestoreMembershipApplication/RestoreMembershipApplicationUseCase.php
src/UseCases/SimpleResponse.php
tests/Integration/UseCases/CancelMembershipApplication/CancelMembershipApplicationUseCaseTest.php
tests/Unit/UseCases/ModerateMembershipApplication/ModerateMembershipApplicationUseCaseTest.php
tests/Unit/UseCases/RestoreMembershipApplication/RestoreMembershipApplicationUseCaseTest.php

These changes will make the controller code in https://github.com/wmde/fundraising-backend/pull/479 shorter because all responses can be handled by one method.

Unify status change responses

---

src/UseCases/ApplyForMembership/ApplicationValidationResult.php
src/UseCases/ApplyForMembership/MembershipApplicationValidator.php
src/UseCases/ValidateMembershipFee/ValidateFeeResult.php
src/UseCases/ValidateMembershipFee/ValidateMembershipFeeUseCase.php
tests/Integration/UseCases/ApplyForMembership/ApplyForMembershipUseCaseTest.php
tests/Unit/UseCases/ApplyForMembership/MembershipApplicationValidatorTest.php
tests/Unit/UseCases/ValidateMembershipFee/ValidateMembershipFeeUseCaseTest.php

- Add property types
- Check interval in Membership validation

fix fee validation

---

src/UseCases/ApplyForMembership/ApplyForMembershipUseCase.php

https://phabricator.wikimedia.org/T277023

Remove mailer TODO

---

.scrutinizer.yml
.travis.yml
composer.json

This version bump is for fixes to the validation regex

Update Payments and Validators

---

src/UseCases/ApplyForMembership/ApplyForMembershipRequest.php
src/UseCases/ValidateMembershipFee/ValidateFeeRequest.php
tests/Unit/UseCases/ApplyForMembership/ApplyForMembershipRequestTest.php
tests/Unit/UseCases/ValidateMembershipFee/ValidateFeeRequestTest.php

This is for https://phabricator.wikimedia.org/T285965

Trim string inputs

---

src/DataAccess/DoctrineApplicationAuthorizer.php
tests/Integration/DataAccess/DoctrineMembershipApplicationAuthorizerTest.php

This is for https://phabricator.wikimedia.org/T288525

Fix authorizer

---

composer.json
src/MembershipContextFactory.php
src/UseCases/ApplyForMembership/MembershipApplicationValidator.php
src/UseCases/HandleSubscriptionPaymentNotification/HandleSubscriptionPaymentNotificationUseCase.php
src/UseCases/HandleSubscriptionSignupNotification/HandleSubscriptionSignupNotificationUseCase.php
tests/Integration/UseCases/ApplyForMembership/ApplyForMembershipUseCaseTest.php

Update PHPStan and fix existing violations.
This will also fix the errors in #92

Update PHPStan to 1.2

---

src/Domain/Model/MembershipApplication.php
src/UseCases/CancelMembershipApplication/CancelMembershipApplicationUseCase.php
tests/Data/ValidMembershipApplication.php
tests/Fixtures/TemplateBasedMailerSpy.php
tests/Integration/UseCases/ApplyForMembership/ApplyForMembershipUseCaseTest.php
tests/Integration/UseCases/CancelMembershipApplication/CancelMembershipApplicationUseCaseTest.php
tests/Unit/Domain/Model/MembershipApplicationTest.php

* Updated the test to the given/when/expect pattern
* Added cancelPaymentUseCase dependency and test case

Cancel membership

---

.docker/database/01_memberships.sql
.docker/database/03_new_payments.sql
check-payment-data.php
composer.json
config/DoctrineClassMapping/WMDE.Fundraising.MembershipContext.DataAccess.DoctrineEntities.MembershipApplication.dcm.xml
docker-compose.yml
migrate-payment-data.php
migrations-db.php
migrations.php
src/DataAccess/Migrations/Version20220609143351.php
src/DataAccess/Migrations/Version20220613122154.php
src/DataAccess/PaymentMigration/BoundedValue.php
src/DataAccess/PaymentMigration/ChunkedQueryResultIterator.php
src/DataAccess/PaymentMigration/ConversionResult.php
src/DataAccess/PaymentMigration/InsertingPaymentHandler.php
src/DataAccess/PaymentMigration/MembershipPaymentIdCollection.php
src/DataAccess/PaymentMigration/MembershipToPaymentConverter.php
src/DataAccess/PaymentMigration/NewPaymentHandler.php
src/DataAccess/PaymentMigration/NullPaymentHandler.php
src/DataAccess/PaymentMigration/ProgressPrinter.php
src/DataAccess/PaymentMigration/ResultObject.php
src/DataAccess/PaymentMigration/SequentialPaymentIdGenerator.php
src/MembershipContextFactory.php
tests/Integration/DataAccess/DoctrineMembershipApplicationAuthorizerTest.php
tests/Integration/DataAccess/DoctrineMembershipApplicationEventLoggerTest.php
tests/TestEnvironment.php
tests/TestMembershipContextFactory.php

This is for https://phabricator.wikimedia.org/T305050

Migrate payments

---

config/DomainClassMapping/WMDE.Fundraising.MembershipContext.Domain.Model.ModerationReason.dcm.xml
src/DataAccess/DoctrineEntities/ModerationIdentifier.php
src/MembershipContextFactory.php

Add "Moderation" prefix to Doctrine type definition to avoid name
clashes with Donation ModerationIdentifier.

Prefix ModerationIdentifier

---

src/DataAccess/PaymentMigration/ChunkedQueryResultIterator.php

This avoids duplicate processing (and database errors resulting from
that) when there are memberships missing and an offset + LIMIT clause
would return already processed memberships. Now we select IDs BETWEEN
offset and offset + chunk_size, guaranteeing that each membership is
only processed once.
This error occurred during https://phabricator.wikimedia.org/T314407

Fix ChunkedQueryResultIterator

---

src/Domain/MembershipPaymentValidator.php

Validation use case for membership fees returns all validation errors, for better user feedback in the front-end
Ticket: https://phabricator.wikimedia.org/T325970

Return more payment validation errors

---

composer.json
config/DoctrineClassMapping/WMDE.Fundraising.MembershipContext.DataAccess.DoctrineEntities.MembershipApplication.dcm.xml
phpunit.xml.dist
src/DataAccess/DoctrineEntities/MembershipApplication.php
src/MembershipContextFactory.php
tests/Integration/DataAccess/DoctrineMembershipApplicationRepositoryTest.php
tests/TestMembershipContextFactory.php

Remove Gedmo Doctrine Extenstions dependency
and configuration.
Memberships now add a created date in the constructor.

Remove Gedmo

---

src/Domain/MembershipPaymentValidator.php
tests/Unit/UseCases/ApplyForMembership/MembershipPaymentValidatorTest.php

https://phabricator.wikimedia.org/T350378

Add FEE_TOO_HIGH validation check

---

composer.json

Make version constraint a bit more loose to allow for feature updates.
Ticket: https://phabricator.wikimedia.org/T350676

Fix composer version constraints

---

src/Domain/Model/MembershipApplication.php
src/Domain/Model/ModerationIdentifier.php
src/UseCases/ApplyForMembership/ApplicantType.php
src/UseCases/ApplyForMembership/ApplyForMembershipUseCase.php
src/UseCases/ApplyForMembership/Moderation/ModerationService.php
tests/Integration/UseCases/ApplyForMembership/ApplyForMembershipUseCaseTest.php
tests/Unit/Domain/Model/MembershipApplicationTest.php
tests/Unit/UseCases/ApplyForMembership/ModerationServiceTest.php

Ticket: https://phabricator.wikimedia.org/T353353

Moderate emails on block list

---

composer.json
src/DataAccess/DoctrineMembershipApplicationEventLogger.php
src/DataAccess/Migrations/Version20220613122154.php
src/DataAccess/PaymentMigration/ChunkedQueryResultIterator.php
src/DataAccess/PaymentMigration/InsertingPaymentHandler.php
src/DataAccess/PaymentMigration/PaymentMigrationCommand.php
src/Domain/Repositories/ApplicationAnonymizedException.php
src/Domain/Repositories/ApplicationRepository.php
src/Domain/Repositories/GetMembershipApplicationException.php
src/Domain/Repositories/StoreMembershipApplicationException.php
src/Infrastructure/MembershipApplicationEventLogException.php
src/Tracking/ApplicationPiwikTracker.php
src/Tracking/ApplicationPiwikTrackingException.php
src/Tracking/ApplicationTracker.php
src/Tracking/ApplicationTrackingException.php
src/UseCases/CancelMembershipApplication/CancellationRequest.php
tests/Integration/DataAccess/DoctrineMembershipApplicationAuthorizerTest.php
tests/Integration/DataAccess/DoctrineMembershipApplicationEventLoggerTest.php
tests/Integration/DataAccess/DoctrineMembershipApplicationTrackerTest.php
tests/Integration/DataAccess/Internal/DoctrineApplicationTableTest.php
tests/TestDoubles/ApplicationRepositorySpy.php
tests/TestDoubles/SucceedingEmailValidator.php
tests/TestDoubles/ThrowingEntityManager.php
tests/Unit/DoctrineEntities/MembershipApplicationTest.php

Ticket: https://phabricator.wikimedia.org/T356744

Update Doctrine ORM

---

.drone.yml

Ticket: https://phabricator.wikimedia.org/T359147

Remove vendor caching from Drone CI

---

.github/dependabot.yml
.gitignore
composer.lock

Ticket: https://phabricator.wikimedia.org/T359146

Track composer.json

---

config/DoctrineClassMapping/WMDE.Fundraising.MembershipContext.DataAccess.DoctrineEntities.MembershipApplication.dcm.xml
src/DataAccess/Migrations/Version20240528122513.php

Add search indexes with a consistent prefix.
Drop unused full text search indices
Ticket: https://phabricator.wikimedia.org/T357527

Improve indexes for address data

---

src/DataAccess/DoctrineMembershipAnonymizer.php

followup for https://github.com/wmde/fundraising-memberships/pull/187

[FollowUp]  Fix naming for array parameters

---

composer.json
composer.lock
src/DataAccess/DoctrineMembershipAnonymizer.php
src/DataAccess/DoctrineMembershipRepository.php
src/Domain/AnonymizationException.php
src/Domain/MembershipAnonymizer.php
src/Domain/Repositories/ApplicationRepository.php
src/Domain/Repositories/MembershipRepository.php
src/UseCases/ApplyForMembership/ApplyForMembershipUseCase.php
src/UseCases/CancelMembershipApplication/CancelMembershipApplicationUseCase.php
src/UseCases/ModerateMembershipApplication/ModerateMembershipApplicationUseCase.php
src/UseCases/RestoreMembershipApplication/RestoreMembershipApplicationUseCase.php
src/UseCases/ShowApplicationConfirmation/ShowApplicationConfirmationUseCase.php
tests/Integration/DataAccess/DoctrineMembershipAnonymizerTest.php
tests/Integration/DataAccess/DoctrineMembershipApplicationRepositoryTest.php
tests/Integration/DataAccess/SerializedDataHandlingTest.php
tests/Integration/UseCases/ApplyForMembership/ApplyForMembershipUseCaseTest.php
tests/Integration/UseCases/CancelMembershipApplication/CancelMembershipApplicationUseCaseTest.php
tests/Integration/UseCases/ShowApplicationConfirmation/ShowApplicationConfirmationUseCaseTest.php
tests/TestDoubles/ApplicationRepositorySpy.php
tests/TestDoubles/FakeMembershipRepository.php
tests/TestDoubles/InMemoryMembershipRepository.php
tests/Unit/UseCases/ModerateMembershipApplication/ModerateMembershipApplicationUseCaseTest.php
tests/Unit/UseCases/RestoreMembershipApplication/RestoreMembershipApplicationUseCaseTest.php

Ticket: https://phabricator.wikimedia.org/T368397

Anonymize memberships

---

composer.json

Require PHP 8.3

---

.github/dependabot.yml

Ticket: https://phabricator.wikimedia.org/T377185

Disable Dependabot Oct-2024

---

.scrutinizer.yml
Makefile
README.md
docker-compose.yml

Ticket: https://phabricator.wikimedia.org/T317957

Prepare for docker compose v2

---

.github/dependabot.yml
composer.lock

-  Update dependencies before re-enabling dependabot

Re-enable dependabot 2025
