src/UseCases/ApplyForMembership/ApplicationValidationResult.php, src/UseCases/ApplyForMembership/MembershipApplicationValidator.php, tests/Unit/UseCases/ApplyForMembership/MembershipApplicationValidatorTest.php
Use "native" validation identifiers from payment domain.
Re-introduce validation of blocked iban which were removed from
IbanValidator in https://github.com/wmde/fundraising-payments/pull/7
This is for https://phabricator.wikimedia.org/T192921
=> Improve payment data validation

composer.json
We might run into API rate limits while requesting our own packages, so
we force composer to actually use the git binary to download the
packages instead of using the GitHub API.
See https://getcomposer.org/doc/05-repositories.md#vcs
=> Prevent composer from using the GitHub API

.travis.yml
There were some GitHub errors for the payment dependency, so for now
we're using the native composer install on Travis.
=> Use native composer on Travis

src/UseCases/ApplyForMembership/ApplicationValidationResult.php, src/UseCases/ApplyForMembership/ApplyForMembershipRequest.php, src/UseCases/ApplyForMembership/MembershipApplicationBuilder.php, src/UseCases/ApplyForMembership/MembershipApplicationValidator.php, src/UseCases/ApplyForMembership/MembershipFeeValidator.php, src/UseCases/ValidateMembershipFee/ValidateFeeRequest.php, src/UseCases/ValidateMembershipFee/ValidateFeeResult.php, src/UseCases/ValidateMembershipFee/ValidateMembershipFeeUseCase.php, tests/Data/ValidMembershipApplicationRequest.php, tests/Integration/UseCases/ApplyForMembership/ApplyForMembershipUseCaseTest.php, tests/Unit/UseCases/ApplyForMembership/MembershipApplicationBuilderTest.php, tests/Unit/UseCases/ApplyForMembership/MembershipApplicationValidatorTest.php, tests/Unit/UseCases/ValidateMembershipFee/ValidateMembershipFeeUseCaseTest.php
I was pointing some people at this component as example and then noticed the MembershipFeeValidator to be violating our own architecture rules. (Which was already indicated by the FIXME.) It is a service that looks private to one UseCase but is used from outside of the Bounded Context. I turned it into a dedicated BC now.
=> Fix architecture violation

composer.json
Using the minor version should suffice and will ease the update pain
when minor, non-BC breaking features are introduced (as in
wmde/FundraisingStore#157)
=> Improve version requirements of FundraisingStore

src/UseCases/ValidateMembershipFee/ValidateFeeResult.php, src/UseCases/ValidateMembershipFee/ValidateMembershipFeeUseCase.php, tests/Unit/UseCases/ValidateMembershipFee/ValidateMembershipFeeUseCaseTest.php
https://phabricator.wikimedia.org/T215163
PP'd with Corinna
=> Fix devision by zero PHP notice

src/UseCases/ApplyForMembership/ApplicationValidationResult.php, src/UseCases/ApplyForMembership/MembershipApplicationValidator.php, tests/Unit/UseCases/ApplyForMembership/MembershipApplicationValidatorTest.php
There was only a client side validation on the membership type,
now there is also server side validation that checks whether
the type is 'active' or 'sustaining'.
=> Add validation for membership type

composer.json
Temporary fix for https://github.com/oradwell/covers-validator/issues/28
=> Downgrade phpunit to fix ci

Makefile
Commit 7e8c849da40f500b2ec9db4539bb969be7401abc increased the possible
PHPStan level without actually increasing it. This commit increases it
in the build process.
=> Increase PHPStan level to 5

migrations/Version20201215000000.php
Add migration that creates the `incentive` and `membership_incentive`
tables.
This commit does not add the doctrine migration library to the bounded
context - migrations are handled by FundraisingFrontend.
This is for https://phabricator.wikimedia.org/T270097
=> Add incentives migration class

src/UseCases/ApplyForMembership/ApplyForMembershipUseCase.php, src/UseCases/ApplyForMembership/MailTemplateValueBuilder.php, tests/Data/ValidMembershipApplication.php, tests/Integration/UseCases/ApplyForMembership/ApplyForMembershipUseCaseTest.php, tests/Unit/UseCases/ApplyForMembership/MailTemplateValueBuilderTest.php
The ApplyForMembershipUseCase now provides the names (string IDs) of the
incentives to the mailer class.
=> Add incentives to mail template values

.travis.yml
Remove `--ignore-platform-reqs` when installing with composer. This
should fix an issue where we install PHP 7.4 incompatible versions
of psr/cache
=> Check platform requirements in Travis

src/DataAccess/DoctrineIncentiveFinder.php, tests/Integration/DataAccess/DoctrineIncentiveFinderTest.php
The DoctrineIncentiveFinder uses the database to find incentives. We
will use this class in production.
This is for https://phabricator.wikimedia.org/T282432
=> Add DoctrineIncentiveFinder

composer.json, src/DataAccess/LegacyConverters/DomainToLegacyConverter.php, src/DataAccess/LegacyConverters/LegacyToDomainConverter.php, src/Domain/Model/MembershipApplication.php, src/UseCases/HandleSubscriptionPaymentNotification/HandleSubscriptionPaymentNotificationUseCase.php, src/UseCases/HandleSubscriptionSignupNotification/HandleSubscriptionSignupNotificationUseCase.php, tests/Data/ValidMembershipApplication.php, tests/Integration/DataAccess/DoctrineMembershipApplicationRepositoryTest.php, tests/Integration/UseCases/HandleSubscriptionSignupNotification/HandleSubscriptionSignupNotificationUseCaseTest.php, tests/Unit/Domain/Model/MembershipApplicationTest.php, tests/Unit/LegacyConverters/DomainToLegacyConverterTest.php
Use new BookablePayment interface to handle payment confirmation.
Use new BookablePayment interface to determine confirmed state.
Add tests for confirmSubscriptionCreated.
Refactor statusAllowsForBooking and remove isDeleted check because that
state of a membership can't be created any more.
=> Improve external payments

.travis.yml, Makefile, docker-compose.yml
https://phabricator.wikimedia.org/T284180
Our old travis file tried to run PHPUnit after is was uninstalled,
leading to a missing coverage report file.
This change add coverage report output flags to the Makefile to
generate HTML by default and Clover XML when run through Travis.
=> Update Travis to upload coverage

src/UseCases/ValidateMembershipFee/ValidateMembershipFeeUseCase.php
When validating user input, check for valid interval lengths. This is an
additional safeguard to prevent a `InvalidArgumentException` (a
logic error, not a runtime error) when constructing membership fees.
=> Improve interval validation

src/UseCases/ApplyForMembership/MembershipApplicationBuilder.php, tests/Fixtures/TestIncentiveFinder.php, tests/Integration/UseCases/ApplyForMembership/ApplyForMembershipUseCaseTest.php, tests/Unit/UseCases/ApplyForMembership/MembershipApplicationBuilderTest.php
https://phabricator.wikimedia.org/T285101
Incentives were being added to the MembershipApplication
without an id. This made Doctrine want to add a new Incentive
when a membership was saved, which caused an error to be thrown.
This fixes that error and adds tests to ensure Incentives have IDs
when added to a MembershipApplication
=> Fix adding incentives to membership applications

composer.json
These shouldn't be there because we don't need test classes in production
=> Remove test files from production autoload

.scrutinizer.yml, .travis.yml
Since the coverage uploader is not compatible with PHP 8, we generate
coverage information with scrutinizer.
=> Remove external coverage from Scrutinizer

composer.json
psr/log must be 2.0 or 3.0 for PHP 8.1, because it has added types.
=> Make dependencies compatible with PHP 8.1

src/UseCases/ShowApplicationConfirmation/ShowApplicationConfirmationPresenter.php, src/UseCases/ShowApplicationConfirmation/ShowApplicationConfirmationUseCase.php, tests/Integration/UseCases/ShowApplicationConfirmation/FakeShowApplicationConfirmationPresenter.php, tests/Integration/UseCases/ShowApplicationConfirmation/ShowApplicationConfirmationUseCaseTest.php
This adds an array parameter to the Confirmation Presenter
to allow it to take in display data from the payment
when implemented in Fundraising Application
Ticket: https://phabricator.wikimedia.org/T305832
=> Add Payment Data to ConfirmationPresenter

src/Domain/MembershipPaymentValidator.php, src/Infrastructure/PaymentServiceFactory.php, src/UseCases/ApplyForMembership/ApplyForMembershipUseCase.php, src/UseCases/ValidateMembershipFee/ValidateMembershipFeeUseCase.php, tests/Integration/UseCases/ApplyForMembership/ApplyForMembershipUseCaseTest.php, tests/Unit/UseCases/ApplyForMembership/MembershipPaymentValidatorTest.php, tests/Unit/UseCases/ValidateMembershipFee/ValidateMembershipFeeUseCaseTest.php
Change MembershipPaymentValidator to check a list of allowed payment
types instead of hard-coding them. The list will be passed from an upper
layer (Fundraising Application) into to PaymentServiceFactory
This is a preparation for https://phabricator.wikimedia.org/T312087
=> Make allowed payment types configurable

src/DataAccess/DoctrineTypes/ModerationIdentifier.php, src/MembershipContextFactory.php
It was misplaced in the DoctrineEntities namespace, but should be in the
DoctrineTypes.
=> Move ModerationIdentifier Doctrine type

bin/check-membership-payment-data, src/DataAccess/PaymentMigration/ConnectionFactory.php, src/DataAccess/PaymentMigration/PaymentMigrationCommand.php
Instead of hard-coding database connection or reading it from the
environment, let's re-use the config file from Doctrine migrations.
This will make it easier to use on the server.
=> Re-use migration db config

composer.json, src/UseCases/RestoreMembershipApplication/RestoreMembershipApplicationUseCase.php, tests/Integration/UseCases/CancelMembershipApplication/CancelMembershipApplicationUseCaseTest.php, tests/Unit/UseCases/RestoreMembershipApplication/RestoreMembershipApplicationUseCaseTest.php
When a membership application is restored by an admin the payment should be un-cancelled.
Ticket: https://phabricator.wikimedia.org/T318217
=> Add payment restore to RestoreMembershipApplication

tests/Integration/UseCases/ApplyForMembership/ApplyForMembershipUseCaseTest.php, tests/Unit/UseCases/ApplyForMembership/MailMembershipApplicationNotifierTest.php
Two tests had the wrong coverage annotations, leading to warnings in CI.
The class `MembershipConfirmationMailer` no longer exists, it was a
duplicate implementation of `MembershipNotifier` and is replaced by
`MailMembershipApplicationNotifier`
ApplyForMembershipUseCaseTest no longer tests the mailer implementation,
so we can simplify the test.
=> Fix coverage information

docker-compose.yml
docker-compose was still using the test release of our container
=> Use default release in docker-compose

src/UseCases/ValidateMembershipFee/ValidateMembershipFeeUseCase.php, tests/Unit/UseCases/ValidateMembershipFee/ValidateMembershipFeeUseCaseTest.php
Handle exceptions from `Euro` class in `ValidateMembershipFeeUseCase`.
Other code (e.g. membership creation) already expects Euro.
I looked at other places (e.g. notifier and DB legacy converter) that
call static `Euro` constructors, but in those cases the amount comes
from sources that other code has already validated, so we should not
catch exceptions there.
=> Handle Euro exceptions

phpunit.xml.dist
PHPUnit should check for `@covers` annotations and/or `#CoversClass` PHP
attributes. This change will allow us to disable the check in our coding
style, which only supports annotations. The coding style rule would
block us from using attributes and PHPUnit 11 in the future.
Ticket: https://phabricator.wikimedia.org/T359971
=> Require coverage metadata in PHPUnit config  

.scrutinizer.yml, Makefile, composer.json, docker-compose.debug.yml
Update all Symfony dependencies to 7.0. These are only dev dependencies.
We allow for 6.x version of the cache to ensure compatibility with an
un-updated payments version.
Checked the CHANGELOG files of each dependency and we don't have any
code that is affected by breaking changes
Remove special PHP 8.1 docker image reference from Makefile and docker-compose.debug.yml
Ticket: https://phabricator.wikimedia.org/T355689
=> Update Symfony to 7.0

src/DataAccess/Migrations/Version20240528122513.php
the column in the db is named m_payment_id, not m_payment
https://phabricator.wikimedia.org/T370649
=> Fix m_payment_id name in migration

src/DataAccess/DoctrineMembershipAnonymizer.php
`anonymizeWithIds` will now check the ID and export state conditions
before anonymizing memberships. This makes the call atomic instead of
best-effort.
Ticket: https://phabricator.wikimedia.org/T357517
=> Pre-check membership anonymization condition

src/DataAccess/DoctrineMembershipRepository.php, src/Domain/Repositories/MembershipRepository.php, src/UseCases/ShowApplicationConfirmation/ShowApplicationConfirmationPresenter.php, src/UseCases/ShowApplicationConfirmation/ShowApplicationConfirmationUseCase.php, tests/Integration/DataAccess/DoctrineMembershipApplicationRepositoryTest.php, tests/Integration/UseCases/ShowApplicationConfirmation/FakeShowApplicationConfirmationPresenter.php, tests/Integration/UseCases/ShowApplicationConfirmation/ShowApplicationConfirmationUseCaseTest.php, tests/TestDoubles/FakeMembershipRepository.php, tests/TestDoubles/InMemoryMembershipRepository.php
The membership confirmation page is now able to handle
anonymised membership applications so we no longer need
to show a separate page.
This adds a method to allow fetching an exported
membership to the MembershipRepository and calls that
in the ShowApplicationConfirmationUseCase.
It also adds/adjusts tests for the above.
Ticket: https://phabricator.wikimedia.org/T316201
=> Allow exported memberships to be fetched

.github/dependabot.yml
- the config item will be removed on May 27, 2025 https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/
=> Remove deprecated `reviewers` config item

src/DataAccess/DoctrineEntities/MembershipApplication.php, src/DataAccess/DoctrineMembershipAuthorizationChecker.php, src/DataAccess/LegacyConverters/DomainToLegacyConverter.php, src/DataAccess/MembershipApplicationData.php, tests/Integration/DataAccess/DoctrineMembershipApplicationRepositoryTest.php, tests/Integration/DataAccess/DoctrineMembershipRepositoryTest.php, tests/Unit/DoctrineEntities/MembershipApplicationTest.php
- Deprecate `MembershipApplicationData` class
- Deprecate accessors of `MembershipApplicationData`
- Deprecate `DoctrineMembershipAuthorizationChecker` - that's now done
with different classes in the applications.
- Remove `preserveDoctrineStatus` method from `DomainToLegacyConverter`.
This was used to preserve the initial membership status
(confirmed/unconfirmed) when restoring canceled memberships. With
the introduction of the payment bounded context, this is now obsolete,
because the restore membership status now fully depends on the payment
state (see `RestoreMembershipApplicationUseCase`).
Ticket: https://phabricator.wikimedia.org/T390844
=> Deprecate auth tokens in data blob

src/UseCases/FeeChange/FeeChangeUseCase.php, src/UseCases/FeeChange/ShowFeeChangePresenter.php, tests/Integration/UseCases/FeeChange/FeeChangeUseCaseTest.php
the UUID is needed in the code that calls the method.
This is a followup for https://github.com/wmde/fundraising-memberships/pull/283
=> Add UUID as parameter
